In [1]:
import pandas as pd
import streamlit as st

from sqlalchemy import create_engine

In [2]:
conn_string = "postgresql://tmshszilbcculx:ee95204861668778837467651b39614a5529edd88412c1fe0a8b9a21419bf437@ec2-54-246-185-161.eu-west-1.compute.amazonaws.com:5432/dd83caln9k71ig"

In [3]:
engine = create_engine(conn_string)

In [4]:
df = pd.read_sql('tracking_logs',con=engine)

In [5]:
df

,log_id,user_id,org_id,course_id,event_type,event_source,ip,date,time,referer
0,1,anonymous,edumaxx,course-v1:edumaxx+EAP0009+FALL_2021_2022,/courses/course-v1:edumaxx+EAP0009+FALL_2021_2...,server,172.16.30.152,2022-03-02,22:09:17,
1,2,anonymous,edumaxx,course-v1:edumaxx+M0003+FALL_2021_2022,/courses/course-v1:edumaxx+M0003+FALL_2021_202...,server,172.16.30.152,2022-03-02,22:30:12,
2,3,anonymous,edumaxx,course-v1:edumaxx+EAP0004+SUMMER_2021_2022,/courses/course-v1:edumaxx+EAP0004+SUMMER_2021...,server,172.16.30.152,2022-03-03,04:16:33,https://www.google.com
3,4,anonymous,edumaxx,course-v1:edumaxx+EAP0005+SPRING_2021_2022,/courses/course-v1:edumaxx+EAP0005+SPRING_2021...,server,172.16.30.152,2022-03-03,04:16:34,https://www.google.com
4,5,anonymous,edumaxx,course-v1:edumaxx+M0006+FALL_2022_2023,/courses/course-v1:edumaxx+M0006+FALL_2022_202...,server,172.16.30.152,2022-03-03,04:16:39,https://www.google.com
...,...,...,...,...,...,...,...,...,...,...
388,389,204,edumaxx,course-v1:edumaxx+M0004+SPRING_2021_2022,/courses/course-v1:edumaxx+M0004+SPRING_2021_2...,server,172.16.30.152,2022-03-05,18:38:19,https://edumaxx.live/courses/course-v1:edumaxx...
389,390,204,edumaxx,course-v1:edumaxx+M0004+SPRING_2021_2022,/courses/course-v1:edumaxx+M0004+SPRING_2021_2...,server,172.16.30.152,2022-03-05,18:38:25,https://edumaxx.live/courses/course-v1:edumaxx...
390,391,204,edumaxx,course-v1:edumaxx+M0004+SPRING_2021_2022,/courses/course-v1:edumaxx+M0004+SPRING_2021_2...,server,172.16.30.152,2022-03-05,18:38:25,https://edumaxx.live/courses/course-v1:edumaxx...
391,392,204,edumaxx,course-v1:edumaxx+M0004+SPRING_2021_2022,seq_goto,browser,172.16.30.152,2022-03-05,18:38:25,https://edumaxx.live/courses/course-v1:edumaxx...
392,393,204,edumaxx,course-v1:edumaxx+M0004+SPRING_2021_2022,/courses/course-v1:edumaxx+M0004+SPRING_2021_2...,server,172.16.30.152,2022-03-05,18:38:30,https://edumaxx.live/courses/course-v1:edumaxx...

In [6]:
engine.dispose()

In [20]:
temp_df = df[df['user_id'] != "anonymous"]

In [21]:
temp_df[['user_id', 'time']]

    user_id                time
7       187 2022-03-03 07:14:47
8       187 2022-03-03 07:14:53
9       187 2022-03-03 07:14:54
10      187 2022-03-03 07:14:57
11      187 2022-03-03 07:15:04
..      ...                 ...
388     204 2022-03-05 18:38:19
389     204 2022-03-05 18:38:25
390     204 2022-03-05 18:38:25
391     204 2022-03-05 18:38:25
392     204 2022-03-05 18:38:30

[311 rows x 2 columns]

In [ ]:
user_df = temp_df[['user_id', 'time']].groupby()

In [15]:
df[df['event_type'] == 'edx.course.enrollment.activated' | df['event_type'] == 'edx.course.enrollment.mode_changed']

TypeError: Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]